#!/usr/bin/python3
#
# Mifare Desfire NFC Python Module
# Copyright (C) 2019  Christian Carlowitz <chca@cmesh.de>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
# for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

""" mdnfc_tool

Usage:
    mdnfc_tool
    mdnfc_tool (-l|--list)

Options:
    -l --list   List tags and contents
"""

import sys
import mdnfc
import time

from docopt import docopt


if __name__ == '__main__':

    args = docopt(__doc__)

    if args["--list"]:

        mdnfc.init()

        tags = mdnfc.list_tags()
        print(tags)
        for t in tags:
            uid = t["uid"]
            print("connecting to tag", uid)
            mdnfc.connect(uid)
            aids = mdnfc.get_appids()
            print(aids)
            mdnfc.disconnect(t)

        mdnfc.deinit()

